import { Education } from '../../types/Education'

export const EDUCATIONS: Education[] = [
   {
      company: 'Babeș-Bolyai University (FSEGA), Cluj-Napoca',
      link: '',
      badges: [],
      title: 'Computer Science & Economics coursework',
      logo: undefined,
      start: '2022',
      end: '2025',
      description: 'Coursework focusing on Computer Science, Information Systems, and Economic Studies.',
   },
   {
      company: 'Google',
      link: '',
      badges: ['AI / Agentic Systems'],
      title: 'AI Agents Intensive Course',
      logo: undefined,
      start: 'Dec 2025',
      end: 'Dec 2025',
      description: 'Intensive course on developing agentic AI workflows and LLM applications.',
   },
   {
      company: 'DeepLearning.AI',
      link: '',
      badges: ['AI / Prompting'],
      title: 'Prompt Engineering for Developers',
      logo: undefined,
      start: '2024',
      end: '2024',
      description: 'Advanced prompt engineering techniques for developer productivity and systems integration.',
   },
   {
      company: 'Udemy',
      link: '',
      badges: ['Frontend'],
      title: 'React – The Complete Guide',
      logo: undefined,
      start: '2023',
      end: '2023',
      description: 'Comprehensive guide covering React Core, Hooks, Redux, React Router, Next.js, and testing.',
   },
   {
      company: 'Coursera',
      link: '',
      badges: ['UI/UX Design'],
      title: 'Google UX Design Fundamentals',
      logo: undefined,
      start: '2022',
      end: '2022',
      description: 'Professional certificate program covering UX research, wireframing, high-fidelity design, and prototyping in Figma.',
   },
]
